# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.7
        env: TOX_ENV=py37
      - python: 3.8
        env: TOX_ENV=py38
      - python: pypy
        env: TOX_ENV=pypy
      - python: 3.6
        env: TOX_ENV=flake8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

deploy:
  provider: pypi
  username: thisch
  password:
    secure: "dQbg17RbX8EtFj7+gc0iHiFQLlfMU7hKORMhXTOumvNOAEedNkb+30MR0mozD6Yv97SX7Lehhs9cPRHg45pzbySsctA20lOU8UkkBnjNyBYzVndNcODD4UlheV+FHXIL5JVk6ySkYkloD+UekPKWMUE6eIidV1v4wQFSbojYnpIjIOblkeSKu4EPotWU5VqMcKr1n5/9m48Tsmje8j+61G0+fym3jz9PkozDSF6c00HgtbwMEMZOCbfrUFQCpTezLTK0v3kMR9xBBojulBS9Dgh3qMNH/AACTkwwa2q9XTANV/bCJfBY41THYzqboQK3ByFNR/s3H6xZ9WgZahNFsKMFQNFAQgFPjxiaOQutxdwxP3Y4AwWmkubyHiEtTv/5Dyw8LuP1zrO3/+uT/XQnRUxBBFbkrUvJRhzlNKZ5p9MX+5MM/wYz4xyyKqFRqrBNujdLu+NvbzKNKx7CHKW0HVdbDmVKdw+Cf4CYTO5o/FMGhd08NYRmFU9ZcXQ+WD7SF+XXnPxRq9NA/VnxDQu97Nofo9NfbbyLh1bh6sv0X1sp44trkoQuOpco2u+85LdIJvJloYXUpJCcbKULUflMUbykZmwWX1NzmYwPvuIFsT2BuZpJDht+LknhuOE9JniWdTx3cQZ5SKZg/w1CvEsD0Xevl7fIAoAmNRaGIx9zFmU="
  on:
    tags: true