# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: test

on:
  push:
    # branches: [ master ]
    paths-ignore:
      - "*.md"
  pull_request:
    # branches: [ master ]
    paths-ignore:
      - "*.md"

jobs:
  testCode:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # TODO only run black / isort on single OS/pyver
        python -m pip install --upgrade pip
        pip install pytest sphinx flake8 tox black isort
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check black formatting
      run: |
        # stop the build if black detect any changes
        black --check .
    - name: Check isort sorting
      run: |
        # stop the build if isort detect any changes
        isort . --check --diff
    - name: Test with pytest
      run: |
        tox -e ci-py -- -v --color=yes

  testUploadability:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    # - name: Test with rstcheck
    #   run: |
    #     rstcheck README.rst
    - name: Build and check
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
